import { describe, expect, it } from 'vitest'
import * as components from '../components'
import * as providers from '../providers'
import { COMPONENT_NAMES, PROVIDER_NAMES } from '../component-names'

/**
 * The name list is generated by a script and committed; the test catches a component added
 * without rerunning the generator.
 */
describe('component-names', () => {
  it('matches the exports of the components barrel', () => {
    expect([...COMPONENT_NAMES].sort()).toEqual(Object.keys(components).sort())
  })

  it('matches the exports of the providers barrel', () => {
    expect([...PROVIDER_NAMES].sort()).toEqual(Object.keys(providers).sort())
  })
})
